export const STR = {
  appTitle: "BetterUnistaller",
  searchPlaceholder: "Rechercher un programme ou un éditeur…",
  loading: "Chargement des programmes…",
  loadError: "Impossible de lire la liste des programmes.",
  emptyResult: "Aucun programme ne correspond.",
  colName: "Nom",
  colPublisher: "Éditeur",
  colVersion: "Version",
  colDate: "Installé le",
  colSize: "Taille",
  filterLarge: "Volumineux (> 1 Go)",
  filterRecent: "Récents (< 30 j)",
  filterNoPublisher: "Sans éditeur",
  filterScopeUser: "Par utilisateur",
  showSystem: "Afficher les entrées système",
  programsCount: (n: number) => `${n} programme${n > 1 ? "s" : ""}`,
  detailOpenFolder: "Ouvrir le dossier d'installation",
  detailTechnical: "Détails techniques",
  detailRegistryKey: "Clé de registre",
  detailUninstallString: "Commande de désinstallation",
  detailNoLocation: "Emplacement inconnu",
  copy: "Copier",
  forceUninstall: "Désinstallation forcée",
  forceUninstallConfirm: (name: string) =>
    `Désinstaller « ${name} » de force ? Un point de restauration système sera créé, les processus du programme seront arrêtés, puis ses fichiers et son entrée de registre seront supprimés. Cette action est réservée aux cas où la désinstallation normale a échoué.`,
  forceUninstallInProgress: "Désinstallation forcée en cours…",
  forceUninstallSuccess: "Programme désinstallé de force.",
  forceUninstallFailure: "La désinstallation forcée a échoué.",
  forceUninstallProtected: (name: string) =>
    `« ${name} » est un composant protégé et ne peut pas être désinstallé de force.`,
  forceUninstallElevationRequested: "Élévation des privilèges demandée…",
} as const;
