export const STR = {
  appTitle: "BetterUnistaller",
  searchPlaceholder: "Rechercher un programme ou un éditeur…",
  loading: "Chargement des programmes…",
  loadError: "Impossible de lire la liste des programmes.",
  emptyResult: "Aucun programme ne correspond.",
  colName: "Nom",
  colPublisher: "Éditeur",
  colVersion: "Version",
  colDate: "Installé le",
  colSize: "Taille",
  filterLarge: "Volumineux (> 1 Go)",
  filterRecent: "Récents (< 30 j)",
  filterNoPublisher: "Sans éditeur",
  filterScopeUser: "Par utilisateur",
  showSystem: "Afficher les entrées système",
  programsCount: (n: number) => `${n} programme${n > 1 ? "s" : ""}`,
  detailOpenFolder: "Ouvrir le dossier d'installation",
  detailTechnical: "Détails techniques",
  detailRegistryKey: "Clé de registre",
  detailUninstallString: "Commande de désinstallation",
  detailNoLocation: "Emplacement inconnu",
  copy: "Copier",
} as const;
